%Alfredo Huerta Sermeño

%plantas
planta(malva).
planta(zarzaparrilla).
planta(anís).
planta(perejil).
planta(sanguinaria).
planta(limon).
planta(sauco).
planta(árnica).
planta(llanten).
planta(fenogreco).
planta(zarzamora).
planta(salvia).
planta(tilo).
planta(valeriana).
planta(yerbabuena).
planta(manzanilla).
planta(jugo_de_limón).
planta(jugo_de_toronja).
planta(pingüica).
planta(quinoa_roja).
planta(encino_rojo).
planta(pimiento).
planta(huramelis).
planta(cola_de_caballo).
planta(arnica).
planta(ajenjo).
planta(germen_de_trigo).
planta(quira).
planta(canela).
planta(alholva).
planta(eucalipto).
planta(cebada).
planta(tabachin).
planta(borraja).
planta(gerciana).
planta(limón).
planta(genciana).
planta(cardo).
planta(chicalote).
planta(alcanfor).
planta(toronja).
planta(merrubio).
planta(toloache).
planta(oregano).
planta(lupulo).
planta(cuasia).
planta(uva).
planta(cerezo).
planta(rosal).
planta(encina).
planta(borraga).
planta(anacahuite).
planta(benjui).
planta(rabano).
planta(ipecacuana).
planta(mostaza).
planta(ortiga).
planta(espinosilla).
planta(romero).
planta(diente_de_león).
planta(aceite_de_oliva).
planta(retama).
planta(cabellos_de_elote).
planta(pinguica).
planta(ajo).
planta(cebolla).
planta(hiedra).
planta(cuachalalate).
planta(siempreviva).
planta(mastuerzo).
planta(higuera).
planta(toronjil).
planta(boldo).
planta(linaza).
planta(laurel).
planta(briania).
planta(nuez_de_kcla).
planta(tejocote).
planta(achicoria).
planta(apio).
planta(sanguinaria).
planta(berro).
planta(matarique).
planta(tronadora).
planta(bucalipto).
planta(damiana).
planta(capulín).
planta(mezquite).
planta(tlalchichinole).
planta(membrillo).
planta(arroz).
planta(guayaba).
planta(albahaca).
planta(granada).
planta(sinionillo).
planta(chaparro_amargoso).
planta(muicle).
planta(monacillo).
planta(naranja).
planta(tamarindo).
planta(quina).
planta(tabequillo).
planta(ruibaxbo).
planta(anís_estrella).
planta(ipecacuana).
planta(cedrón).
planta(té_de_limón).
planta(genciana).
%plantas según asignación
planta(grama).
planta(granado).
planta(gordolobo).

%Significado de las propiedades de las plantas
propiedad(afrodisiaca).
propiedad(analgesica).
propiedad(anestesica).
propiedad(antidiarreica).
propiedad(antiespasmodica).
propiedad(antiflogistica).
propiedad(antipiretica).
propiedad(antiseptica).
propiedad(aperitiva).
propiedad(astringente).
propiedad(carminativa).
propiedad(colagoga).
propiedad(depurativa).
propiedad(diaforetica).
propiedad(digestiva).
propiedad(diuretica).
propiedad(emetica).
propiedad(emenagoga).
propiedad(estupefaciente).
propiedad(hemostatica).
propiedad(hepatica).
propiedad(laxante).
propiedad(pectoral).
propiedad(sedante).
propiedad(tonica).
propiedad(toxica).
propiedad(vermifuga).
propiedad(vulneraria).

%Padecimientos
padecimiento(abscesos).
padecimiento(absceso_hepático).
padecimiento(acidez_estomacal).
padecimiento(ácido_úrico).
padecimiento(acné).
padecimiento(aftas).
padecimiento(agotamiento).
padecimiento(agruras).
padecimiento(albuminaria).
padecimiento(alcoholismo).
padecimiento(almorranas).
padecimiento(anemia).
padecimiento(anginas).
padecimiento(anorexia).
padecimiento(arterosclerosis).
padecimiento(artritis).
padecimiento(asma).
padecimiento(atonia_estomacal).
padecimiento(bazo).
padecimiento(inflamación_de_la_boca).
padecimiento(estomatitis).
padecimiento(bronquitis).
padecimiento(bronconeumonia).
padecimiento(caida_del_cabello).
padecimiento(calambres).
padecimiento(cálculos_biliares).
padecimiento(cálculos_renales).
padecimiento(callos).
padecimiento(caries).
padecimiento(caspa).
padecimiento(cancer_de_útero).
padecimiento(ciática).
padecimiento(circulación).
padecimiento(cistitis).
padecimiento(cólicos).
padecimiento(colitis).
padecimiento(contusiones).
padecimiento(corazón).
padecimiento(depurativos_de_la_sangre).

padecimiento(golpes_internos).
padecimiento(infeccion_en_los_riñones).
padecimiento(mal_de_orin).
padecimiento(inflamaciones_en_general).
padecimiento(lombrices).


%Usos de las plantas
usado_para_tratar(malva,abscesos).
usado_para_tratar(zarzaparrilla,absceso_hepático).
usado_para_tratar(anís,acidez_estomacal).
usado_para_tratar(perejil,acidez_estomacal).
usado_para_tratar(sanguinaria,ácido_úrico).
usado_para_tratar(limón,ácido_úrico).
usado_para_tratar(sauco,ácido_úrico).
usado_para_tratar(árnica,acné).
usado_para_tratar(llanten,aftas).
usado_para_tratar(fenogreco,aftas).
usado_para_tratar(zarzamora,aftas).
usado_para_tratar(salvia,agotamiento).
usado_para_tratar(tilo,agotamiento).
usado_para_tratar(valeriana,agotamiento).
usado_para_tratar(yerbabuena,agruras).
usado_para_tratar(manzanilla,agruras).
usado_para_tratar(jugo_de_limón,agruras).
usado_para_tratar(jugo_de_toronja,agruras).
usado_para_tratar(pingüica,albuminaria).
usado_para_tratar(quinoa_roja,albuminaria).
usado_para_tratar(encino_rojo,albuminaria).
usado_para_tratar(pimiento,alcoholismo).
usado_para_tratar(salvia,almorranas).
usado_para_tratar(huramelis,almorranas).
usado_para_tratar(sanguinaria,almorranas).
usado_para_tratar(cola_de_caballo,almorranas).
usado_para_tratar(arnica,almorranas).
usado_para_tratar(sauco,almorranas).
usado_para_tratar(ajenjo,anemia).
usado_para_tratar(germen_de_trigo,anemia).
usado_para_tratar(quira,anemia).
usado_para_tratar(canela,anemia).
usado_para_tratar(alholva,anemia).
usado_para_tratar(eucalipto,anginas).
usado_para_tratar(cebada,anginas).
usado_para_tratar(salvia,anginas).
usado_para_tratar(tabachin,anginas).
usado_para_tratar(borraja,anginas).
usado_para_tratar(ajenjo,anorexia).
usado_para_tratar(gerciana,anorexia).
usado_para_tratar(yerbabuena,anorexia).
usado_para_tratar(limón,arterosclerosis).
usado_para_tratar(genciana,arterosclerosis).
usado_para_tratar(cardo,arterosclerosis).
usado_para_tratar(zarzaparrilla,arterosclerosis).
usado_para_tratar(arnica,arterosclerosis).
usado_para_tratar(chicalote,arterosclerosis).
usado_para_tratar(alcanfor,arterosclerosis).
usado_para_tratar(toronja,arterosclerosis).
usado_para_tratar(limón,artritis).
usado_para_tratar(genciana,artritis).
usado_para_tratar(cardo,artritis).
usado_para_tratar(zarzaparrilla,artritis).
usado_para_tratar(arnica,artritis).
usado_para_tratar(chicalote,artritis).
usado_para_tratar(alcanfor,artritis).
usado_para_tratar(toronja,artritis).
usado_para_tratar(eucalipto,asma).
usado_para_tratar(merrubio,asma).
usado_para_tratar(toloache,asma).
usado_para_tratar(oregano,asma).
usado_para_tratar(salvia,asma).
usado_para_tratar(gordolobo,asma).
usado_para_tratar(lupulo,atonia_estomacal).
usado_para_tratar(eucalipto,atonia_estomacal).
usado_para_tratar(cuasia,atonia_estomacal).
usado_para_tratar(uva,bazo).
usado_para_tratar(cerezo,bazo).
usado_para_tratar(malva,inflamación_de_la_boca).
usado_para_tratar(rosal,inflamación_de_la_boca).
usado_para_tratar(limón,inflamación_de_la_boca).
usado_para_tratar(salvia,inflamación_de_la_boca).
usado_para_tratar(rosal,estomatitis).
usado_para_tratar(encina,estomatitis).
usado_para_tratar(salvia,estomatitis).
usado_para_tratar(zarzamora,estomatitis).
usado_para_tratar(eucalipto,bronquitis).
usado_para_tratar(borraga,bronquitis).
usado_para_tratar(anacahuite,bronquitis).
usado_para_tratar(gordolobo,bronquitis).
usado_para_tratar(tilo,bronquitis).
usado_para_tratar(benjui,bronquitis).
usado_para_tratar(marrubio,bronquitis).
usado_para_tratar(rabano,bronquitis).
usado_para_tratar(gordolobo,bronconeumonia).
usado_para_tratar(eucalipto,bronconeumonia).
usado_para_tratar(ipecacuana,bronconeumonia).
usado_para_tratar(mostaza,bronconeumonia).
usado_para_tratar(ortiga,caida_del_cabello).
usado_para_tratar(espinosilla,caida_del_cabello).
usado_para_tratar(marrubio,caida_del_cabello).
usado_para_tratar(romero,caida_del_cabello).
usado_para_tratar(anís,calambres).
usado_para_tratar(tila,calambres).
usado_para_tratar(manzanilla,calambres).
usado_para_tratar(ajenjo,calambres).
usado_para_tratar(diente_de_león,cálculos_biliares).
usado_para_tratar(aceite_de_oliva,cálculos_biliares).
usado_para_tratar(retama,cálculos_biliares).
usado_para_tratar(cabellos_de_elote,cálculos_renales).
usado_para_tratar(pinguica,cálculos_renales).
usado_para_tratar(cola_de_caballo,cálculos_renales).
usado_para_tratar(ajo,callos).
usado_para_tratar(cebolla,callos).
usado_para_tratar(hiedra,caries).
usado_para_tratar(cola_de_caballo,caries).
usado_para_tratar(ortiga,caspa).
usado_para_tratar(limón,caspa).
usado_para_tratar(romero,caspa).
usado_para_tratar(cuachalalate,cancer_de_útero).
usado_para_tratar(llanten,cancer_de_útero).
usado_para_tratar(siempreviva,cancer_de_útero).
usado_para_tratar(mastuerzo,ciática).
usado_para_tratar(higuera,ciática).
usado_para_tratar(sauco,ciática).
usado_para_tratar(toronjil,circulación).
usado_para_tratar(sanguinaria,circulación).
usado_para_tratar(salvia,circulación).
usado_para_tratar(hamamelis,circulación).
usado_para_tratar(cola_de_caballo,cistitis).
usado_para_tratar(doradilla,cistitis).
usado_para_tratar(ajo,cistitis).
usado_para_tratar(cabellos_de_elote,cistitis).
usado_para_tratar(menta,cólicos).
usado_para_tratar(hinojo,cólicos).
usado_para_tratar(manzanilla,cólicos).
usado_para_tratar(toronjil,cólicos).
usado_para_tratar(boldo,cólicos).
usado_para_tratar(linaza,colitis).
usado_para_tratar(anís,colitis).
usado_para_tratar(romero,colitis).
usado_para_tratar(cola_de_caballo,colitis).
usado_para_tratar(árnica,contusiones).
usado_para_tratar(hamamelis,contusiones).
usado_para_tratar(laurel,contusiones).
usado_para_tratar(briania,contusiones).
usado_para_tratar(digital,corazón).
usado_para_tratar(salvia,corazón).
usado_para_tratar(nuez_de_kcla,corazón).
usado_para_tratar(tejocote,corazón).
usado_para_tratar(achicoria,depurativos_de_la_sangre).
usado_para_tratar(diente_de_león,depurativos_de_la_sangre).
usado_para_tratar(apio,depurativos_de_la_sangre).
usado_para_tratar(sanguinaria,depurativos_de_la_sangre).
usado_para_tratar(zarzaparrilla,depurativos_de_la_sangre).
usado_para_tratar(berro,depurativos_de_la_sangre).
usado_para_tratar(matarique,diabetes).
usado_para_tratar(tronadora,diabetes).
usado_para_tratar(bucalipto,diabetes).
usado_para_tratar(damiana,diabetes).
usado_para_tratar(capulín,diarrea_crónica).
usado_para_tratar(mezquite,diarrea_crónica).
usado_para_tratar(tlalchichinole,diarrea_crónica).
usado_para_tratar(linaza,diarrea_por_irritación).
usado_para_tratar(membrillo,diarrea_por_irritación).
usado_para_tratar(arroz,diarrea_por_irritación).
usado_para_tratar(cebada,diarrea_por_irritación).
usado_para_tratar(guayaba,diarrea_por_inflamación).
usado_para_tratar(albahaca,diarrea_por_inflamación).
usado_para_tratar(granada,diarrea_por_inflamación).
usado_para_tratar(manzanilla,diarrea_verdosa).
usado_para_tratar(sinionillo,diarrea_verdosa).
usado_para_tratar(siempreviva,diarrea_verdosa).
usado_para_tratar(chaparro_amargoso,diarrea_con_sangre).
usado_para_tratar(muicle,diarrea_con_sangre).
usado_para_tratar(monacillo,diarrea_con_sangre).
usado_para_tratar(limón,difteria).
usado_para_tratar(naranja,difteria).
usado_para_tratar(tamarindo,disentería).
usado_para_tratar(chaparro_amargoso,disentería).
usado_para_tratar(ipecacuana,disentería).
usado_para_tratar(cedrón,disentería).
usado_para_tratar(anís,dispepsia).
usado_para_tratar(menta,dispepsia).
usado_para_tratar(yerbabuena,dispepsia).
usado_para_tratar(diente_de_león,dispepsia).
usado_para_tratar(té_de_limón,dispepsia).
usado_para_tratar(quina,dispepsia).
usado_para_tratar(genciana,dispepsia).
usado_para_tratar(tabequillo,dispepsia).
usado_para_tratar(ruibaxbo,dispepsia).
usado_para_tratar(anís_estrella,dolor).
usado_para_tratar(valeriana,dolor).
usado_para_tratar(manzanilla,dolor).
usado_para_tratar(alcanfor,dolores_musculares).
usado_para_tratar(tamarindo,empacho).
usado_para_tratar(linaza,enteritis).
usado_para_tratar(cedrón,enteritis).
usado_para_tratar(llanten,enteritis).
usado_para_tratar(valeriana,epilepsia).
usado_para_tratar(hierba_del_pollo,epistaxis).
usado_para_tratar(cebolla,epistaxis).
usado_para_tratar(perejil,epistaxis).
usado_para_tratar(sauco,erisipela).
usado_para_tratar(hiedra,erisipela).
usado_para_tratar(zanahoria,erisipela).
usado_para_tratar(borraja,escarlatina).
usado_para_tratar(sauco,escarlatina).
usado_para_tratar(cebolla,escarlatina).
usado_para_tratar(ajo,escorbuto).
usado_para_tratar(limón,escorbuto).
usado_para_tratar(berro,escorbuto).
usado_para_tratar(cebolla,escorbuto).
usado_para_tratar(geranio,escorbuto).
usado_para_tratar(ciruela,estreñimiento).
usado_para_tratar(linaza,estreñimiento).
usado_para_tratar(chía,estreñimiento).
usado_para_tratar(tamarindo,estreñimiento).
usado_para_tratar(agar_agar,estreñimiento).
usado_para_tratar(eucalipto,faringitis).
usado_para_tratar(lavanda,faringitis).
usado_para_tratar(anacahuite,faringitis).
usado_para_tratar(apio,flatulencia).
usado_para_tratar(tomillo,flatulencia).
usado_para_tratar(perejil,flatulencia).
usado_para_tratar(anís,flatulencia).
usado_para_tratar(hinojo,flatulencia).
usado_para_tratar(toronjil,flatulencia).
usado_para_tratar(romero,flatulencia).
usado_para_tratar(ruibarbo,flatulencia).
usado_para_tratar(ruda,flatulencia).
usado_para_tratar(menta,flatulencia).
usado_para_tratar(ármica,flebitis).
usado_para_tratar(alfalfa_,flebitis).
usado_para_tratar(lino,flebitis).
usado_para_tratar(malvavisco,flebitis).
usado_para_tratar(romero,flebitis).
usado_para_tratar(quina,flebitis).
usado_para_tratar(genciana_,flemas).
usado_para_tratar(orégano,flemas).
usado_para_tratar(fenogreco,forúnculos).
usado_para_tratar(malvavisco,forúnculos).
usado_para_tratar(hiedra,forúnculos).
usado_para_tratar(manzanilla,gastralgia).
usado_para_tratar(anís_de_estrella,gastralgia).
usado_para_tratar(cola_de_caballo,gonorrea).
usado_para_tratar(doradilla,gonorrea).
usado_para_tratar(zarzaparrilla,gonorrea).
usado_para_tratar(apio,gota).
usado_para_tratar(cerezo,gota).
usado_para_tratar(limón,gota).
usado_para_tratar(pino,gota).
usado_para_tratar(alcanfor,gota).
usado_para_tratar(aconito,gota).
usado_para_tratar(belladona,gota).
usado_para_tratar(beleño,gota).
usado_para_tratar(colchico,gota).
usado_para_tratar(chicalote,gota).
usado_para_tratar(encina,grietas_del_ano).
usado_para_tratar(encina,grietas_del_pezón).
usado_para_tratar(nogal,grietas_del_pezón).
usado_para_tratar(milenrana,grietas_del_pezón).
usado_para_tratar(eucalipto,gripe).
usado_para_tratar(limón,gripe).
usado_para_tratar(quina,gripe).
usado_para_tratar(zarzaparrilla,gripe).
usado_para_tratar(calendula,gripe).
usado_para_tratar(hinojo,halitosis).
usado_para_tratar(menta,halitosis).
usado_para_tratar(mastuerzo,hemorraga_interna).
usado_para_tratar(ortiga,hemorraga_interna).
usado_para_tratar(rosal,hemorraga_interna).
usado_para_tratar(retama,hepatitis).
usado_para_tratar(boldo,hepatitis).
usado_para_tratar(alcachofa,hepatitis).
usado_para_tratar(prodigiosa,hepatitis).
usado_para_tratar(cáscara_sagrada,hepatitis).
usado_para_tratar(helecho,hernia).
usado_para_tratar(ricino,hernia).
usado_para_tratar(tabaco,hernia).
usado_para_tratar(linaza,herpes).
usado_para_tratar(llanten,herpes).
usado_para_tratar(árnica_,heridas).
usado_para_tratar(hamamelis,heridas).
usado_para_tratar(alcachofa,hidropesia).
usado_para_tratar(cardo,hidropesia).
usado_para_tratar(perejil,hidropesia).
usado_para_tratar(sauco,hidropesia).
usado_para_tratar(berros,hidropesia).
usado_para_tratar(retama,hidropesia).
usado_para_tratar(marrubio,congestion_en_el_higado).
usado_para_tratar(boldo,congestion_en_el_higado).
usado_para_tratar(doradilla,congestion_en_el_higado).
usado_para_tratar(ruibarbo,congestion_en_el_higado).
usado_para_tratar(manzanilla,colico).
usado_para_tratar(lechuga,bilis).
usado_para_tratar(tila,bilis).
usado_para_tratar(papoloquelite,letericia).
usado_para_tratar(achicoria,letericia).
usado_para_tratar(berros,letericia).
usado_para_tratar(llanten,letericia).
usado_para_tratar(retama,letericia).
usado_para_tratar(tecomasuchil,letericia).
usado_para_tratar(ajo,hipertensión).
usado_para_tratar(esparrago,hipertensión).
usado_para_tratar(alpiste,hipertensión).
usado_para_tratar(muerdago,hipertensión).
usado_para_tratar(miel,hipotensión).
usado_para_tratar(nuez_de_kola,hipotensión).
usado_para_tratar(crategus,hipotensión).
usado_para_tratar(acedera,hipotensión).
usado_para_tratar(anís,hipo).
usado_para_tratar(hinojo,hipo).
usado_para_tratar(tila,hipo).
usado_para_tratar(valeriana,hipo).
usado_para_tratar(azahar,histerismo).
usado_para_tratar(beleño,histerismo).
usado_para_tratar(gelsenio,histerismo).
usado_para_tratar(tila,histerismo).
usado_para_tratar(valeriana,histerismo).
usado_para_tratar(pastiflora,insómio).
usado_para_tratar(azahar,insómio).
usado_para_tratar(menta,insómio).
usado_para_tratar(manzanilla,insómio).
usado_para_tratar(lechuga,insómio).
usado_para_tratar(genciana_,intestino).
usado_para_tratar(melisa,intestino).
usado_para_tratar(yohimbo,impotencia_sexual).
usado_para_tratar(damiana,impotencia_sexual).
usado_para_tratar(nuex_vómica,impotencia_sexual).
usado_para_tratar(aguacate,impotencia_sexual).
usado_para_tratar(manzanilla,jaqueca).
usado_para_tratar(acónito,jaqueca).
usado_para_tratar(valeriana,jaqueca).
usado_para_tratar(tila,jaqueca).
usado_para_tratar(chicalote,jaqueca).
usado_para_tratar(hinojo,lactancia).
usado_para_tratar(anís,lactancia).
usado_para_tratar(menta,lactancia).
usado_para_tratar(perejil,lactancia).
usado_para_tratar(zanahoria,lactancia).
usado_para_tratar(acónito,laringitis).
usado_para_tratar(borraja,laringitis).
usado_para_tratar(cebolla,laringitis).
usado_para_tratar(rosal,laringitis).
usado_para_tratar(benjui,laringitis).
usado_para_tratar(encina,laringitis).
usado_para_tratar(encina,leucorrea).
usado_para_tratar(zarzaparrilla,leucorrea).
usado_para_tratar(pino,leucorrea).
usado_para_tratar(enebro,leucorrea).
usado_para_tratar(genciana_,leucorrea).
usado_para_tratar(ajenjo,lombrices).
usado_para_tratar(ajo,lombrices).
usado_para_tratar(cebolla,lombrices).
usado_para_tratar(brionia,lombrices).
usado_para_tratar(aguacate,lombrices).
usado_para_tratar(papaya,lombrices).
usado_para_tratar(avena,lumbago).
usado_para_tratar(cebada,lumbago).
usado_para_tratar(tomillo,lumbago).
usado_para_tratar(verbena,lumbago).
usado_para_tratar(fenogreco,llagas).
usado_para_tratar(eucalipto,llagas).
usado_para_tratar(llanten,llagas).
usado_para_tratar(sanguinaria,llagas).
usado_para_tratar(quina,malaria).
usado_para_tratar(girasol,malaria).
usado_para_tratar(eucalipto,malaria).
usado_para_tratar(cardo,malaria).
usado_para_tratar(azahar,menopausia).
usado_para_tratar(hamamelis,menopausia).
usado_para_tratar(tila,menopausia).
usado_para_tratar(quina_roja,menopausia).
usado_para_tratar(azafrán,menstruación).
usado_para_tratar(hamamelis,menstruación).
usado_para_tratar(belladona,menstruación).
usado_para_tratar(anís_de_estrella,menstruación).
usado_para_tratar(ruda,menstruación).
usado_para_tratar(ajenjo,menstruación).
usado_para_tratar(manzanilla,menstruación).
usado_para_tratar(apio,menstruación).
usado_para_tratar(hisopol,menstruación).
usado_para_tratar(quina_amarilla,menstruación).
usado_para_tratar(sabina,menstruación).
usado_para_tratar(artemisa,menstruación).
usado_para_tratar(hamamelis,metorragia).
usado_para_tratar(zoapatle,metorragia).
usado_para_tratar(perejil,metorragia).
usado_para_tratar(cuercillo,metorragia).
usado_para_tratar(clavo,muelas).
usado_para_tratar(heidra,muelas).
usado_para_tratar(ortiga,nariz).
usado_para_tratar(cola_de_caballo,nariz).
usado_para_tratar(ruda,nariz).
usado_para_tratar(eucalipto,nariz).
usado_para_tratar(anís,náuseas).
usado_para_tratar(ajenjo,náuseas).
usado_para_tratar(menta,náuseas).
usado_para_tratar(salvia,náuseas).
usado_para_tratar(manzanilla,neuralgias).
usado_para_tratar(menta,neuralgias).
usado_para_tratar(valeriana,neuralgias).
usado_para_tratar(bolde,neuralgias).
usado_para_tratar(rasiflora,neurastenia).
usado_para_tratar(té_negro,neurastenia).
usado_para_tratar(mate,neurastenia).
usado_para_tratar(valeriana,neurastenia).
usado_para_tratar(linaza,nefritis).
usado_para_tratar(grama,nefritis).
usado_para_tratar(cebada,nefritis).
usado_para_tratar(llanten,nefritis).
usado_para_tratar(doradilla,nefritis).
usado_para_tratar(espárrago_ruda,nefritis).
usado_para_tratar(toronjil,obesidad).
usado_para_tratar(marrubio,obesidad).
usado_para_tratar(limón,obesidad).
usado_para_tratar(malva,obesidad).
usado_para_tratar(esparrago,obesidad).
usado_para_tratar(boldo,oídos).
usado_para_tratar(aceite_de_oliva,oídos).
usado_para_tratar(llanten,oídos).
usado_para_tratar(hiedra,oídos).
usado_para_tratar(manzanilla,conjuntivitis).
usado_para_tratar(limón,conjuntivitis).
usado_para_tratar(llanten,conjuntivitis).
usado_para_tratar(salvia,conjuntivitis).
usado_para_tratar(ruda,conjuntivitis).
usado_para_tratar(rosal,conjuntivitis).
usado_para_tratar(ajenjo,paludismo).
usado_para_tratar(quina,paludismo).
usado_para_tratar(berros,pecas).
usado_para_tratar(genciana_,pecas).
usado_para_tratar(rabano,pecas).
usado_para_tratar(papaija,pecas).
usado_para_tratar(laurel,pies_olorosos).
usado_para_tratar(encina,pies_olorosos).
usado_para_tratar(miel,piquetes).
usado_para_tratar(perejil,piquetes).
usado_para_tratar(cebolla,piquetes).
usado_para_tratar(puerro,piquetes).
usado_para_tratar(fresno,piquetes).
usado_para_tratar(ipecacuana,piquetes).
usado_para_tratar(alcanfor,piquetes).
usado_para_tratar(perejil,piquetes).
usado_para_tratar(hamamelis,piquetes).
usado_para_tratar(anagálida,piquetes).
usado_para_tratar(jengibre,pleuresia).
usado_para_tratar(linaza,pleuresia).
usado_para_tratar(cardo,pleuresia).
usado_para_tratar(girasol,pleuresia).
usado_para_tratar(ipecacuana,piorrea).
usado_para_tratar(cola_de_caballo,próstata).
usado_para_tratar(eucalipto,pulmonía).
usado_para_tratar(ocote,pulmonía).
usado_para_tratar(gordolobo,pulmonía).
usado_para_tratar(borraja,pulmonía).
usado_para_tratar(sauco,pulmonía).
usado_para_tratar(linaza,quemaduras).
usado_para_tratar(cebolla,quemaduras).
usado_para_tratar(hiedra,quemaduras).
usado_para_tratar(gordolobo,quemaduras).
usado_para_tratar(nogal,raquitismo).
usado_para_tratar(ajo,reumatismo).
usado_para_tratar(apio,reumatismo).
usado_para_tratar(borraja,reumatismo).
usado_para_tratar(gobernadora,reumatismo).
usado_para_tratar(pino,reumatismo).
usado_para_tratar(romero,reumatismo).
usado_para_tratar(sanguinaria,reumatismo).
usado_para_tratar(marrubio,reumatismo).
usado_para_tratar(tabaco,reumatismo).
usado_para_tratar(cabellos_de_elote,riñones).
usado_para_tratar(cola_de_caballo,riñones).
usado_para_tratar(apio,riñones).
usado_para_tratar(eucalipto,ronquera).
usado_para_tratar(pino,ronquera).
usado_para_tratar(gordolobo,ronquera).
usado_para_tratar(ajo,ronquera).
usado_para_tratar(cebolla,ronquera).
usado_para_tratar(estafiate,san_vito).
usado_para_tratar(valeriana,san_vito).
usado_para_tratar(borraja,sarampión).
usado_para_tratar(ortiga,sarampión).
usado_para_tratar(sauco,sarampión).
usado_para_tratar(ajo,sarna).
usado_para_tratar(alcanfor,sarna).
usado_para_tratar(menta,sarna).
usado_para_tratar(tomillo,sarna).
usado_para_tratar(romero,sarna).
usado_para_tratar(encina,sarpullido).
usado_para_tratar(salvia,sarpullido).
usado_para_tratar(tila,sarpullido).
usado_para_tratar(limón,sed).
usado_para_tratar(tamarindo,sed).
usado_para_tratar(pirúl,sed).
usado_para_tratar(semilla_de_calabaza,solitaria).
usado_para_tratar(coquito_de_aceite,solitaria).
usado_para_tratar(helecho_macho,solitaria).
usado_para_tratar(encina,sudoración_escesiva).
usado_para_tratar(alcanfor,tifoidea).
usado_para_tratar(borraja,tifoidea).
usado_para_tratar(quina_,tifoidea).
usado_para_tratar(canela,tifoidea).
usado_para_tratar(romero,tifoidea).
usado_para_tratar(salvia,tifoidea).
usado_para_tratar(berro_,tiña).
usado_para_tratar(tamarindo,tiña).
usado_para_tratar(salvia,tiña).
usado_para_tratar(eucalipto,tos).
usado_para_tratar(capulín,tos).
usado_para_tratar(cedrón,tos).
usado_para_tratar(salvia,tos).
usado_para_tratar(malva,tos).
usado_para_tratar(marrubio,tos).
usado_para_tratar(gordolobo,tos).
usado_para_tratar(gelsemio,tos_ferina).
usado_para_tratar(quina,tos_ferina).
usado_para_tratar(rábano,tos_ferina).
usado_para_tratar(violeta,tos_ferina).
usado_para_tratar(jugo_de_vástago_de_plátano_morado,tuberculosis).
usado_para_tratar(mastuerzo,tuberculosis).
usado_para_tratar(berro,tuberculosis).
usado_para_tratar(ajo,tuberculosis).
usado_para_tratar(eucalipto,tuberculosis).
usado_para_tratar(pirúl,tuberculosis).
usado_para_tratar(pino,tuberculosis).
usado_para_tratar(roble,tuberculosis).
usado_para_tratar(cuachalalate,úlcera).
usado_para_tratar(sanguinaria,úlcera).
usado_para_tratar(cola_de_caballo,úlcera).
usado_para_tratar(girasol,úlcera).
usado_para_tratar(limón,urticaria).
usado_para_tratar(ruibarbo,urticaria).
usado_para_tratar(hamamelis,várices).
usado_para_tratar(castaño_de_indias,várices).
usado_para_tratar(llanten,várices).
usado_para_tratar(toronjil,várices).
usado_para_tratar(gordolobo,várices).
usado_para_tratar(apio,vejiga).
usado_para_tratar(cipres,vejiga).
usado_para_tratar(cola_de_caballo,vejiga).
usado_para_tratar(ortiga,vejiga).
usado_para_tratar(malva,vejiga).
usado_para_tratar(leche_de_higuera,verrugas).
usado_para_tratar(cebolla,verrugas).
usado_para_tratar(nogal,verrugas).
usado_para_tratar(albahaca,vértigos).
usado_para_tratar(espino,vértigos).
usado_para_tratar(menta,vómitos).
usado_para_tratar(tila,vómitos).
usado_para_tratar(marrubio,vómitos).
usado_para_tratar(valeriana,vómitos).
usado_para_tratar(salvia,vómitos).
usado_para_tratar(cilantro,voz).
usado_para_tratar(ajo,voz).
usado_para_tratar(limón,voz).
usado_para_tratar(pino,voz).
usado_para_tratar(alfalfa,vitaminas).
usado_para_tratar(espinacas,vitaminas).
usado_para_tratar(acelga,vitaminas).
usado_para_tratar(berro,vitaminas).
usado_para_tratar(cebolla,vitaminas).
usado_para_tratar(limón,vitaminas).
usado_para_tratar(zanahoria,vitaminas).

usado_para_tratar(abrojo,afecciones_del_pecho).
usado_para_tratar(abrojo,inflamacion_de_los_ojos).
usado_para_tratar(abrojo,inflamacion_del_higado).
usado_para_tratar(abrojo,favorece_circulacion_de_la_sangre).
usado_para_tratar(acacia, garganta_estropeada).
usado_para_tratar(acacia, quemaduras).
usado_para_tratar(acacia, bronquitis).
usado_para_tratar(acacia, tos).
usado_para_tratar(acacia, dolor_de_garganta).
usado_para_tratar(acanto, picadura_de_araña).
usado_para_tratar(acanto, desinflamar).
usado_para_tratar(acanto, sacar_veneno).
usado_para_tratar(acanto, almorranas).
usado_para_tratar(acanto, ardores_de_orina).
usado_para_tratar(acanto, heridas_por_golpe_o_caída).
usado_para_tratar(acanto, dispepsia).
usado_para_tratar(acanto, disentería).
usado_para_tratar(aceitilla,cansancio_intelectual).
usado_para_tratar(aceitilla,depresion_nerviosa).
usado_para_tratar(aceitilla,mujer_histerica).
usado_para_tratar(aceitilla,mujer_con_muchos_nervios).
usado_para_tratar(aceitilla,tonicidad_nerviosa).
usado_para_tratar(aceitilla,tonicidad_cerebral).
usado_para_tratar(achicoria,diuretico).
usado_para_tratar(achicoria,depurativo).
usado_para_tratar(achicoria,dificil_digestion).
usado_para_tratar(achicoria,colicos_biliosos).
usado_para_tratar(achicoria,estreñimiento).
usado_para_tratar(gordolobo,hemorroides).

%plantas según asignación
usado_para_tratar(grama,curar_golpes_internos).
usado_para_tratar(grama,infeccion_en_los_riñones).
usado_para_tratar(grama,mal_de_orin).
usado_para_tratar(grama,inflamaciones_en_general).
usado_para_tratar(granado,lombrices).


%Significado de palabras segun lo que hace la planta
significa(afrodisiaca,exita_el_apetito_sexual).
significa(analgesica,quita_o_modera_el_dolor).
significa(anestesica,insensibiliza_el_cuerpo).
significa(antidiarreica,controla_diarreas).
significa(antiespasmodica,controla_espasmos_nerviosos).
significa(antiflogistica,ayuda_con_inflamaciones).
significa(antipiretica,quita_la_fiebre).
significa(antiseptica,mata_los_tejidos).
significa(aperitiva,deseo_de_comer).
significa(astringente,contrae_los_tejidos).
significa(carminativa,evita_formacion_de_gases).
significa(colagoga,ayuda_a_expulsar_la_bilis).
significa(depurativa,limpia_y_purifica_la_sangre).
significa(diaforetica,provoca_sudoracion_como_cochino).
significa(digestiva,favorece_a_la_digestion).
significa(diuretica,provoca_la_orina).
significa(emetica,provoca_nauseas_y_vomitos).
significa(emenagoga,activa_la_menstruacion).
significa(estupefaciente,ayuda_a_tranquilizar).
significa(hemostatica,detiene_las_hemorragias).
significa(hepatica,ayuda_al_higado).
significa(laxante,purga_sin_provocar_diarrea).
significa(pectoral,ayuda_al_pecho).
significa(sedante,calma_dolores_intestinales).
significa(tonica,fortalece_el_organismo).
significa(toxica,es_venenosa).
significa(vermifuga,expulsa_gusanos_intestinales).
significa(vulneraria,cura_llagas_y_heridas).

%Medicamentos producidos con las diferentes plantas.
produce(digital,tonico_cardiaco).
produce(opio,morfina).
produce(ipeca,emetina).
produce(nuez_vomica,estrienica).
produce(eleboro_blanco,veratrina).
produce(colchico,colquicina).
produce(belladona,atropina).
produce(quina,quina).
produce(cacao,teobromina).
produce(retama,esparteina).
produce(coca,cocaina).
produce(peyote,mescalina).
produce(efedra,efedrina).
produce(barrasco,hormonas).
produce(nenufar_amarillo,lutenurina).
produce(artemisa,tauremisina).
produce(semilla_de_yute,olitorisida).
produce(toloache,acido_lisergico).
produce(eucalipto,eucaliptol).
produce(rosal,vitamina_c).

%Modo de empleo de las plantas
modo_de_empleo(abrojo,usar_como_agua_de_uso).
modo_de_empleo(acacia, chupar_savia_seca_o_hacer_polvos).
modo_de_empleo(acanto,aplicar_hojas_sobre_la_zona_afectada).
modo_de_empleo(acanto,hacer_té_con_las_hojas).
modo_de_empleo(aceitilla,hacer_te_con_la_planta).
modo_de_empleo(achicora,hacer_te_con_las_hojas_secas).
%plantas según asignación
modo_de_empleo(gordolobo,hacer_un_te).
modo_de_empleo(grama,agua_de_uso).
modo_de_empleo(granado, hervir_la_raiz_del_granado_hasta_que_se_consuma_la_tercera_parte_del_agua_y_tomada_en_ayunas).

% Regla que relaciona la propiedad afrodisiaca con su significado
tiene_propiedad_con_significado(X, Y) :- propiedad(X), significa(X, Y).
